[+] Urgent Push

diff --git a/.github/workflows/mirror.yml b/.github/workflows/mirror.yml
--- a/.github/workflows/mirror.yml
+++ b/.github/workflows/mirror.yml
@@ -19,43 +19,43 @@ jobs:
     - name: Install jq
       run: sudo apt-get install -y jq
 
-    - name: Trigger Jenkins Build
-      env:
-        JENKINS_URL: ${{ secrets.JENKINS_URL }}
-        JENKINS_USER: ${{ secrets.JENKINS_USER }}
-        JENKINS_API_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}
-        JENKINS_JOB_NAME: ${{ secrets.JENKINS_JOB_NAME }}
-      run: |
-        build_url="${JENKINS_URL}${JENKINS_JOB_NAME}/build"
-        job_response=$(curl -s -X POST "$build_url" --user ${JENKINS_USER}:${JENKINS_API_TOKEN})
+    # - name: Trigger Jenkins Build
+    #   env:
+    #     JENKINS_URL: ${{ secrets.JENKINS_URL }}
+    #     JENKINS_USER: ${{ secrets.JENKINS_USER }}
+    #     JENKINS_API_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}
+    #     JENKINS_JOB_NAME: ${{ secrets.JENKINS_JOB_NAME }}
+    #   run: |
+    #     build_url="${JENKINS_URL}${JENKINS_JOB_NAME}/build"
+    #     job_response=$(curl -s -X POST "$build_url" --user ${JENKINS_USER}:${JENKINS_API_TOKEN})
 
-        sleep 7
+    #     sleep 7
 
-        last_build_number=$(curl -s "${JENKINS_URL}${JENKINS_JOB_NAME}/lastBuild/buildNumber" --user ${JENKINS_USER}:${JENKINS_API_TOKEN})
+    #     last_build_number=$(curl -s "${JENKINS_URL}${JENKINS_JOB_NAME}/lastBuild/buildNumber" --user ${JENKINS_USER}:${JENKINS_API_TOKEN})
 
-        while true; do
-          BUILD_STATUS=$(curl -s "${JENKINS_URL}${JENKINS_JOB_NAME}/${last_build_number}/api/json" --user ${JENKINS_USER}:${JENKINS_API_TOKEN} | jq -r '.result')
-          if [ "$BUILD_STATUS" == "SUCCESS" ]; then
-            echo "Build succeeded."
-            echo "BUILD_STATUS=SUCCESS" >> $GITHUB_ENV
-            exit 0
-          elif [ "$BUILD_STATUS" == "FAILURE" ]; then
-            echo "Build failed."
-            echo "BUILD_STATUS=FAILURE" >> $GITHUB_ENV
-            exit 1
-          elif [ "$BUILD_STATUS" == "ABORTED" ]; then
-            echo "Build was aborted."
-            echo "BUILD_STATUS=ABORTED" >> $GITHUB_ENV
-            exit 1
-          elif [ "$BUILD_STATUS" == "null" ]; then
-            echo "Build is still running..."
-          else
-            echo "Unknown build status: $BUILD_STATUS"
-            echo "BUILD_STATUS=UNKNOWN" >> $GITHUB_ENV
-            exit 1
-          fi
-          sleep 5
-        done
+    #     while true; do
+    #       BUILD_STATUS=$(curl -s "${JENKINS_URL}${JENKINS_JOB_NAME}/${last_build_number}/api/json" --user ${JENKINS_USER}:${JENKINS_API_TOKEN} | jq -r '.result')
+    #       if [ "$BUILD_STATUS" == "SUCCESS" ]; then
+    #         echo "Build succeeded."
+    #         echo "BUILD_STATUS=SUCCESS" >> $GITHUB_ENV
+    #         exit 0
+    #       elif [ "$BUILD_STATUS" == "FAILURE" ]; then
+    #         echo "Build failed."
+    #         echo "BUILD_STATUS=FAILURE" >> $GITHUB_ENV
+    #         exit 1
+    #       elif [ "$BUILD_STATUS" == "ABORTED" ]; then
+    #         echo "Build was aborted."
+    #         echo "BUILD_STATUS=ABORTED" >> $GITHUB_ENV
+    #         exit 1
+    #       elif [ "$BUILD_STATUS" == "null" ]; then
+    #         echo "Build is still running..."
+    #       else
+    #         echo "Unknown build status: $BUILD_STATUS"
+    #         echo "BUILD_STATUS=UNKNOWN" >> $GITHUB_ENV
+    #         exit 1
+    #       fi
+    #       sleep 5
+    #     done
 
     - name: Sync with Private Repository
       # if: env.BUILD_STATUS == 'SUCCESS'
